version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: ruzhova/backend:v1
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  frontend:
    image: ruzhova/frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/static/
      - media_value:/media/recipes/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  static_value:
  media_value: